name: mainza
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - nodejs=18
  - npm
  - neo4j=5.15
  - redis
  - pytest
  - pytest-cov
  - pytest-asyncio
  - bandit
  - safety
  - pip:
    - fastapi>=0.100.0
    - uvicorn[standard]>=0.23.0
    - neo4j>=5.11.0
    - pydantic>=2.0.0
    - pydantic-ai>=0.2.0
    - pydantic-settings>=2.0.0
    - openai-whisper
    - TTS>=0.22.0
    - sentence-transformers>=2.2.2
    - requests>=2.31.0
    - python-jose>=3.3.0
    - python-dotenv>=1.0.0
    - livekit-api>=1.0.0
    - bcrypt>=4.0.0
    - torch>=2.1.0
    - transformers<4.50
    - semgrep
