name: mainza
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytest
  - pytest-cov
  - pytest-asyncio
  - bandit
  - safety
  - pip:
    - fastapi>=0.100.0
    - uvicorn[standard]>=0.23.0
    - neo4j>=5.11.0
    - pydantic>=2.0.0
    - pydantic-ai>=0.2.0
    - pydantic-settings>=2.0.0
    - requests>=2.31.0
    - python-jose>=3.3.0
    - python-dotenv>=1.0.0
    - bcrypt>=4.0.0
    - semgrep
